spring:
  application:
    name: SPRING-ADMIN-SERVER
  #──────────────────────────────────────────────────────────────────────────────────────────
  # 스프링시큐리티설정
  #──────────────────────────────────────────────────────────────────────────────────────────
  security:
    user:
      name: test-user
      password: test-password